server:
  port: 3000

spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: web-tech
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update